import type {
  SupportAccessMode,
  SupportContactKind,
  SupportCountry,
  SupportDataStatus,
} from '@vbyg/contracts';

export type SeedSupportContact = {
  id: string;
  country: SupportCountry;
  countryLabel: string;
  kind: SupportContactKind;
  title: string;
  description: string;
  displayValue: string;
  actionUri: string;
  actionLabel: string;
  accessMode: SupportAccessMode;
  accessLabel: string;
  dataStatus: SupportDataStatus;
  dataStatusLabel: string;
  sourceOwner: string;
  sourceUrl: string;
  languages: string[];
  hours: string;
  lastReviewedAt: Date;
  nextReviewAt: Date;
  sortOrder: number;
  isActive: boolean;
};

const lastReviewedAt = new Date('2026-08-12T00:00:00.000Z');
const nextReviewAt = new Date('2026-09-12T00:00:00.000Z');

export const seedSupportContacts: readonly SeedSupportContact[] = [
  {
    id: 'support-cambodia-1288',
    country: 'cambodia',
    countryLabel: 'Cambodia',
    kind: 'emergency',
    title: 'Anti-trafficking hotline, Cambodia',
    description: 'Human-trafficking reporting short code listed by Cambodia’s telecommunications regulator.',
    displayValue: '1288',
    actionUri: 'tel:1288',
    actionLabel: 'Call 1288',
    accessMode: 'cellular',
    accessLabel: 'No data · cellular service required',
    dataStatus: 'reviewed-reference',
    dataStatusLabel: 'Reviewed emergency reference',
    sourceOwner: 'Telecommunication Regulator of Cambodia',
    sourceUrl: 'https://www.trc.gov.kh/en/resources/emergency-numbers/',
    languages: ['Confirm with provider'],
    hours: 'Availability not independently confirmed',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'support-cambodia-117',
    country: 'cambodia',
    countryLabel: 'Cambodia',
    kind: 'emergency',
    title: 'Police. 119 for an ambulance',
    description: 'Cambodia police emergency short code; the official directory lists 119 for ambulance.',
    displayValue: '117',
    actionUri: 'tel:117',
    actionLabel: 'Call 117',
    accessMode: 'cellular',
    accessLabel: 'No data · cellular service required',
    dataStatus: 'reviewed-reference',
    dataStatusLabel: 'Reviewed emergency reference',
    sourceOwner: 'Telecommunication Regulator of Cambodia',
    sourceUrl: 'https://www.trc.gov.kh/en/resources/emergency-numbers/',
    languages: ['Confirm with provider'],
    hours: 'Availability not independently confirmed',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'support-cambodia-vietnam-embassy',
    country: 'cambodia',
    countryLabel: 'Cambodia',
    kind: 'embassy',
    title: 'Vietnamese embassy, Phnom Penh',
    description: 'Official public switchboard for the Embassy of Viet Nam in Phnom Penh.',
    displayValue: '+855 23 726 274',
    actionUri: 'tel:+85523726274',
    actionLabel: 'Call the embassy',
    accessMode: 'cellular',
    accessLabel: 'No data · cellular service required',
    dataStatus: 'reviewed-reference',
    dataStatusLabel: 'Reviewed official reference',
    sourceOwner: 'Ministry of Foreign Affairs of Viet Nam',
    sourceUrl: 'https://vnembassy-phnompenh.mofa.gov.vn/en/lien-he',
    languages: ['Confirm with embassy'],
    hours: 'Opening hours not confirmed in this prototype',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 30,
    isActive: true,
  },
  {
    id: 'support-cambodia-chab-dai',
    country: 'cambodia',
    countryLabel: 'Cambodia',
    kind: 'organization',
    title: 'Someone to help you get out and home',
    description: 'Open Chab Dai’s official contact page for current support and referral information.',
    displayValue: 'Chab Dai Coalition',
    actionUri: 'https://www.chabdai.org/contact',
    actionLabel: 'Open Chab Dai',
    accessMode: 'internet',
    accessLabel: 'Internet connection required',
    dataStatus: 'synthetic-summary',
    dataStatusLabel: 'Synthetic prototype summary',
    sourceOwner: 'Chab Dai Coalition',
    sourceUrl: 'https://www.chabdai.org/contact',
    languages: ['English'],
    hours: 'Response hours not confirmed',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 40,
    isActive: true,
  },
  {
    id: 'support-cambodia-legal-aid',
    country: 'cambodia',
    countryLabel: 'Cambodia',
    kind: 'organization',
    title: 'A free lawyer if your papers were taken',
    description: 'Open Legal Aid of Cambodia’s official site to check current eligibility and contact options.',
    displayValue: 'Legal Aid of Cambodia',
    actionUri: 'https://lackhmer.org/',
    actionLabel: 'Open Legal Aid of Cambodia',
    accessMode: 'internet',
    accessLabel: 'Internet connection required',
    dataStatus: 'synthetic-summary',
    dataStatusLabel: 'Synthetic prototype summary',
    sourceOwner: 'Legal Aid of Cambodia',
    sourceUrl: 'https://lackhmer.org/',
    languages: ['Khmer', 'English'],
    hours: 'Response hours not confirmed',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 50,
    isActive: true,
  },
  {
    id: 'support-vietnam-111',
    country: 'vietnam',
    countryLabel: 'Viet Nam',
    kind: 'emergency',
    title: 'National protection hotline, Viet Nam',
    description: 'National hotline that accepts child-protection and human-trafficking reports.',
    displayValue: '111',
    actionUri: 'tel:111',
    actionLabel: 'Call 111',
    accessMode: 'cellular',
    accessLabel: 'No data · cellular service required',
    dataStatus: 'reviewed-reference',
    dataStatusLabel: 'Reviewed emergency reference',
    sourceOwner: 'Ministry of Health of Viet Nam',
    sourceUrl: 'https://moh.gov.vn/tin-noi-bat/-/asset_publisher/3Yst7YhbkA5j/content/thu-truong-bo-y-te-nguyen-tri-thuc-du-khai-truong-tong-ai-ien-thoai-quoc-gia-ve-phong-chong-mua-ban-nguoi-111',
    languages: ['Vietnamese'],
    hours: 'Availability not independently confirmed',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'support-vietnam-113',
    country: 'vietnam',
    countryLabel: 'Viet Nam',
    kind: 'emergency',
    title: 'Police. 115 for an ambulance',
    description: 'Viet Nam police emergency short code; 115 is used for medical emergencies.',
    displayValue: '113',
    actionUri: 'tel:113',
    actionLabel: 'Call 113',
    accessMode: 'cellular',
    accessLabel: 'No data · cellular service required',
    dataStatus: 'reviewed-reference',
    dataStatusLabel: 'Reviewed emergency reference',
    sourceOwner: 'Ministry of Public Security of Viet Nam',
    sourceUrl: 'https://www.mps.gov.vn/bai-viet/moi-lam-viec-01-cong-dan-nhieu-lan-goi-dien-quay-roi-so-113-1782459200',
    languages: ['Vietnamese'],
    hours: 'Emergency service',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'support-vietnam-blue-dragon',
    country: 'vietnam',
    countryLabel: 'Viet Nam',
    kind: 'organization',
    title: 'Help in Vietnamese, from Viet Nam',
    description: 'Open Blue Dragon’s official contact page for current case-support information.',
    displayValue: 'Blue Dragon Children’s Foundation',
    actionUri: 'https://www.bluedragon.org/who-we-are/contact-us/',
    actionLabel: 'Open Blue Dragon',
    accessMode: 'internet',
    accessLabel: 'Internet connection required',
    dataStatus: 'synthetic-summary',
    dataStatusLabel: 'Synthetic prototype summary',
    sourceOwner: 'Blue Dragon Children’s Foundation',
    sourceUrl: 'https://www.bluedragon.org/who-we-are/contact-us/',
    languages: ['Vietnamese', 'English'],
    hours: 'Vietnam business hours; not monitored 24/7',
    lastReviewedAt,
    nextReviewAt,
    sortOrder: 30,
    isActive: true,
  },
] as const;
