import {
  SUPPORT_BUNDLE_AVAILABILITY_NOTICE,
  SupportDirectoryBundleSchema,
} from '@vbyg/contracts';

const reviewedAt = '2026-08-12T00:00:00.000Z';
const nextReviewAt = '2026-09-12T00:00:00.000Z';
const cambodiaEmergencySource = 'https://www.trc.gov.kh/en/resources/emergency-numbers/';
const vietnamEmergencySource = 'https://congbaocdn.chinhphu.vn/CongBaoCP/VanBan/2022/3/36965/40179-1-2022289-29004-vbhn-btttt.pdf';
const directoryNotice =
  'This directory does not monitor emergencies or verify that help is currently available. Contact and location sharing happen only when you choose an action.' as const;

const emergencyDefaults = {
  accessMode: 'cellular' as const,
  accessLabel: 'No data · cellular service required',
  dataStatus: 'reviewed-reference' as const,
  dataStatusLabel: 'Reviewed emergency reference',
  languages: [],
  languageStatus: 'unconfirmed' as const,
  hours: 'Hours not stated in the reviewed source',
  lastReviewedAt: reviewedAt,
  nextReviewAt,
  reviewStatus: 'current' as const,
};

export const bundledSupportDirectory = SupportDirectoryBundleSchema.parse({
  bundleSchemaVersion: 1,
  bundledAt: reviewedAt,
  availabilityNotice: SUPPORT_BUNDLE_AVAILABILITY_NOTICE,
  response: {
    schemaVersion: 1,
    fetchedAt: reviewedAt,
    directoryNotice,
    contacts: [
      {
        ...emergencyDefaults,
        id: 'support-cambodia-117',
        country: 'cambodia',
        countryLabel: 'Cambodia',
        kind: 'emergency',
        title: 'Police, Cambodia',
        description: 'Police emergency short code listed by Cambodia’s telecommunications regulator.',
        displayValue: '117',
        actionUri: 'tel:117',
        actionLabel: 'Call 117',
        sourceOwner: 'Telecommunication Regulator of Cambodia',
        sourceUrl: cambodiaEmergencySource,
        sortOrder: 10,
      },
      {
        ...emergencyDefaults,
        id: 'support-cambodia-119',
        country: 'cambodia',
        countryLabel: 'Cambodia',
        kind: 'emergency',
        title: 'Ambulance, Cambodia',
        description: 'Ambulance emergency short code listed by Cambodia’s telecommunications regulator.',
        displayValue: '119',
        actionUri: 'tel:119',
        actionLabel: 'Call 119',
        sourceOwner: 'Telecommunication Regulator of Cambodia',
        sourceUrl: cambodiaEmergencySource,
        sortOrder: 20,
      },
      {
        ...emergencyDefaults,
        id: 'support-cambodia-1288',
        country: 'cambodia',
        countryLabel: 'Cambodia',
        kind: 'emergency',
        title: 'Anti-trafficking hotline, Cambodia',
        description: 'Human-trafficking reporting short code listed by Cambodia’s telecommunications regulator.',
        displayValue: '1288',
        actionUri: 'tel:1288',
        actionLabel: 'Call 1288',
        sourceOwner: 'Telecommunication Regulator of Cambodia',
        sourceUrl: cambodiaEmergencySource,
        sortOrder: 30,
      },
      {
        id: 'support-cambodia-vietnam-embassy',
        country: 'cambodia',
        countryLabel: 'Cambodia',
        kind: 'embassy',
        title: 'Vietnamese Embassy switchboard',
        description: 'General contact number listed by the Embassy of Viet Nam in Cambodia.',
        displayValue: '+855 23 726 274',
        actionUri: 'tel:+85523726274',
        actionLabel: 'Call the embassy',
        accessMode: 'cellular',
        accessLabel: 'No data · cellular service required',
        dataStatus: 'reviewed-reference',
        dataStatusLabel: 'Reviewed official reference',
        sourceOwner: 'Ministry of Foreign Affairs of Viet Nam',
        sourceUrl: 'https://vnembassy-phnompenh.mofa.gov.vn/en/lien-he',
        languages: [],
        languageStatus: 'unconfirmed',
        hours: 'Hours not stated in the reviewed source',
        lastReviewedAt: reviewedAt,
        nextReviewAt,
        reviewStatus: 'current',
        sortOrder: 40,
      },
      {
        id: 'support-cambodia-chab-dai',
        country: 'cambodia',
        countryLabel: 'Cambodia',
        kind: 'organization',
        title: 'Chab Dai support and referrals',
        description: 'Open Chab Dai’s official contact page for current support and referral information.',
        displayValue: 'Chab Dai Coalition',
        actionUri: 'https://www.chabdai.org/contact',
        actionLabel: 'Open Chab Dai',
        accessMode: 'internet',
        accessLabel: 'Internet connection required',
        dataStatus: 'reviewed-reference',
        dataStatusLabel: 'Reviewed organization reference',
        sourceOwner: 'Chab Dai Coalition',
        sourceUrl: 'https://www.chabdai.org/contact',
        languages: [],
        languageStatus: 'unconfirmed',
        hours: 'Hours not stated in the reviewed source',
        lastReviewedAt: reviewedAt,
        nextReviewAt,
        reviewStatus: 'current',
        sortOrder: 50,
      },
      {
        ...emergencyDefaults,
        id: 'support-vietnam-113',
        country: 'vietnam',
        countryLabel: 'Viet Nam',
        kind: 'emergency',
        title: 'Police, Viet Nam',
        description: 'Nationwide police emergency short code in the official numbering plan.',
        displayValue: '113',
        actionUri: 'tel:113',
        actionLabel: 'Call 113',
        sourceOwner: 'Government of Viet Nam official gazette',
        sourceUrl: vietnamEmergencySource,
        sortOrder: 10,
      },
      {
        ...emergencyDefaults,
        id: 'support-vietnam-115',
        country: 'vietnam',
        countryLabel: 'Viet Nam',
        kind: 'emergency',
        title: 'Medical emergency, Viet Nam',
        description: 'Nationwide medical-emergency short code in the official numbering plan.',
        displayValue: '115',
        actionUri: 'tel:115',
        actionLabel: 'Call 115',
        sourceOwner: 'Government of Viet Nam official gazette',
        sourceUrl: vietnamEmergencySource,
        sortOrder: 20,
      },
      {
        ...emergencyDefaults,
        id: 'support-vietnam-111',
        country: 'vietnam',
        countryLabel: 'Viet Nam',
        kind: 'emergency',
        title: 'National protection and anti-trafficking hotline',
        description: 'National hotline for child protection and reports or information about human trafficking.',
        displayValue: '111',
        actionUri: 'tel:111',
        actionLabel: 'Call 111',
        sourceOwner: 'Viet Nam National Hotline 111',
        sourceUrl: 'https://tongdai111.vn/tin/tong-dai-dien-thoai-quoc-gia-ve-phong-chong-mua-ban-nguoi-la-so111',
        hours: '24/7 according to the reviewed source',
        sortOrder: 30,
      },
      {
        id: 'support-vietnam-consular-guidance',
        country: 'vietnam',
        countryLabel: 'Viet Nam',
        kind: 'consular',
        title: 'Viet Nam Consular Department guidance',
        description: 'Open the official Consular Department route for current citizen-protection guidance and contacts.',
        displayValue: 'Consular and citizen-protection guidance',
        actionUri: 'https://mofa.gov.vn/web/ministry-of-foreign-affairs/consular-services',
        actionLabel: 'Open consular guidance',
        accessMode: 'internet',
        accessLabel: 'Internet connection required',
        dataStatus: 'reviewed-reference',
        dataStatusLabel: 'Reviewed official reference',
        sourceOwner: 'Ministry of Foreign Affairs of Viet Nam',
        sourceUrl: 'https://mofa.gov.vn/web/ministry-of-foreign-affairs/consular-services',
        languages: [],
        languageStatus: 'unconfirmed',
        hours: 'Hours not stated in the reviewed source',
        lastReviewedAt: reviewedAt,
        nextReviewAt,
        reviewStatus: 'current',
        sortOrder: 40,
      },
      {
        id: 'support-vietnam-blue-dragon',
        country: 'vietnam',
        countryLabel: 'Viet Nam',
        kind: 'organization',
        title: 'Blue Dragon support',
        description: 'Open Blue Dragon’s official contact page for current case-support information.',
        displayValue: 'Blue Dragon Children’s Foundation',
        actionUri: 'https://www.bluedragon.org/who-we-are/contact-us/',
        actionLabel: 'Open Blue Dragon',
        accessMode: 'internet',
        accessLabel: 'Internet connection required',
        dataStatus: 'reviewed-reference',
        dataStatusLabel: 'Reviewed organization reference',
        sourceOwner: 'Blue Dragon Children’s Foundation',
        sourceUrl: 'https://www.bluedragon.org/who-we-are/contact-us/',
        languages: [],
        languageStatus: 'unconfirmed',
        hours: 'Not monitored 24/7; see the official contact page',
        lastReviewedAt: reviewedAt,
        nextReviewAt,
        reviewStatus: 'current',
        sortOrder: 50,
      },
    ],
  },
});
